name: Run Checker Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Python3 & Valgrind)
        run: |
          sudo apt update
          sudo apt install -y python3 valgrind

      - name: Run implementation correctness tests
        working-directory: ./checker
        run: python3 checker.py --all 2>&1 | tee test_output.txt

      - name: Run memory check with Valgrind
        working-directory: ./checker
        run: python3 checker.py --all --valgrind 2>&1 | tee valgrind_output.txt
      
      - name: Coding Style checker
        run: |
          chmod +x ./checker/coding-style/checkpatch.pl ./checker/coding-style/cs.sh
          ./checker/coding-style/cs.sh src/ 2>&1 | tee checker/coding_style.txt

      - name: Upload test logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checker-logs
          path: |
            checker/test_output.txt
            checker/valgrind_output.txt
            checker/coding_style.txt
          retention-days: 30

