name: Run Checker Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Python3 & Valgrind)
        run: |
          sudo apt update
          sudo apt install -y python3 valgrind

      - name: Run implementation correctness tests
        working-directory: ./checker
        run: python3 checker.py --all | tee test_output.txt

      - name: Run memory check with Valgrind
        working-directory: ./checker
        run: python3 checker.py --all --valgrind | tee valgrind_output.txt

      - name: Upload test logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: checker-logs
          path: |
            checker/test_output.txt
            checker/valgrind_output.txt
          retention-days: 21
