name: Run Checker Tests on C-Method-2

on:
  push:
    branches: main
    paths: ['tests_data/**', '.github/workflows/**', 'C-method-2/**']
  pull_request:
    branches: main
    paths: ['tests_data/**', '.github/workflows/**', 'C-method-2/**']

  schedule:
    # Overnight: run tests every Friday at 23:15 UTC
    # cron <minute> <hour> <day-of-month> <day-of-week (sunday=0)>
    - cron: "15 23 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Python3 & Valgrind)
        run: |
          sudo apt update
          sudo apt install -y python3 valgrind

      - name: Run implementation tests & memory check with Valgrind
        working-directory: ./C-method-2/tests
        run: python3 checker.py --all --valgrind --output 2>&1 | tee test_results.txt
      
      - name: Coding Style checker
        # directory not specified => running from repo's root
        run: |
          chmod +x ./C-coding-style/checkpatch.pl ./C-coding-style/cs.sh
          ./C-coding-style/cs.sh C-method-2/src 2>&1 | tee ./C-method-2/tests/coding_style.txt

      - name: Upload test logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checker-logs
          path: |
            C-method-2/tests/test_results.txt
            C-method-2/tests/coding_style.txt
            # Without `*` globbing, folders files will not be uploaded
            tests_data/output-C-method-2/*
            tests_data/valgrind_logs-C-method-2/*
          retention-days: 5
